import { Action } from "redux"

export enum ACTIONS {
  // @WARNING change EXTENSION_ by the real extension name
  EXTENSION_RESET_STATE = "EXTENSION_RESET_STATE",
  EXTENSION_SET_SERVER_EXTENSION_VERSION = "EXTENSION_SET_SERVER_EXTENSION_VERSION",
  EXTENSION_SET_FAVOURITE_IS_LOADING = "EXTENSION_SET_FAVOURITE_IS_LOADING",
  EXTENSION_SET_FAVOURITE_HAS_LOADING_ERROR = "EXTENSION_SET_FAVOURITE_HAS_LOADING_ERROR",
  EXTENSION_SET_ALL_FAVOURITE = "EXTENSION_SET_ALL_FAVOURITE",
  EXTENSION_ADD_FAVOURITE = "EXTENSION_ADD_FAVOURITE",
  EXTENSION_DELETE_FAVOURITE = "EXTENSION_DELETE_FAVOURITE",
  EXTENSION_SET_DASHBOARD_IS_LOADING = "EXTENSION_SET_DASHBOARD_IS_LOADING",
  EXTENSION_SET_DASHBOARD_HAS_LOADING_ERROR = "EXTENSION_SET_DASHBOARD_HAS_LOADING_ERROR",
  EXTENSION_SET_ALL_DASHBOARD = "EXTENSION_SET_ALL_DASHBOARD",
  EXTENSION_ADD_DASHBOARD = "EXTENSION_ADD_DASHBOARD",
  EXTENSION_DELETE_DASHBOARD = "EXTENSION_DELETE_DASHBOARD"
}

export interface JExtSetServerExtensionVersion extends Action {
  serverExtensionVersion: string
}

export const extensionActionCreator = {
  resetState(): Action {
    return {
      type: ACTIONS.EXTENSION_RESET_STATE
    }
  },
  setServerExtensionVersion(serverExtensionVersion: string): JExtSetServerExtensionVersion {
    return {
      type: ACTIONS.EXTENSION_RESET_STATE,
      serverExtensionVersion
    }
  }
}
